#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_QLPM.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_QLPM")]
	public partial class QLPM_ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBENH(BENH instance);
    partial void UpdateBENH(BENH instance);
    partial void DeleteBENH(BENH instance);
    partial void InsertCACHDUNG(CACHDUNG instance);
    partial void UpdateCACHDUNG(CACHDUNG instance);
    partial void DeleteCACHDUNG(CACHDUNG instance);
    partial void InsertDONVI(DONVI instance);
    partial void UpdateDONVI(DONVI instance);
    partial void DeleteDONVI(DONVI instance);
    partial void InsertHOSOBENHNHAN(HOSOBENHNHAN instance);
    partial void UpdateHOSOBENHNHAN(HOSOBENHNHAN instance);
    partial void DeleteHOSOBENHNHAN(HOSOBENHNHAN instance);
    partial void InsertTHAMSO(THAMSO instance);
    partial void UpdateTHAMSO(THAMSO instance);
    partial void DeleteTHAMSO(THAMSO instance);
    partial void InsertPHIEUNHAPTHUOC(PHIEUNHAPTHUOC instance);
    partial void UpdatePHIEUNHAPTHUOC(PHIEUNHAPTHUOC instance);
    partial void DeletePHIEUNHAPTHUOC(PHIEUNHAPTHUOC instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertPHIEUKHAMBENH(PHIEUKHAMBENH instance);
    partial void UpdatePHIEUKHAMBENH(PHIEUKHAMBENH instance);
    partial void DeletePHIEUKHAMBENH(PHIEUKHAMBENH instance);
    partial void InsertCT_PHIEUNHAPTHUOC(CT_PHIEUNHAPTHUOC instance);
    partial void UpdateCT_PHIEUNHAPTHUOC(CT_PHIEUNHAPTHUOC instance);
    partial void DeleteCT_PHIEUNHAPTHUOC(CT_PHIEUNHAPTHUOC instance);
    partial void InsertCT_PHIEUKHAMBENH(CT_PHIEUKHAMBENH instance);
    partial void UpdateCT_PHIEUKHAMBENH(CT_PHIEUKHAMBENH instance);
    partial void DeleteCT_PHIEUKHAMBENH(CT_PHIEUKHAMBENH instance);
    partial void InsertTHUOC(THUOC instance);
    partial void UpdateTHUOC(THUOC instance);
    partial void DeleteTHUOC(THUOC instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    #endregion
		
		public QLPM_ModelDataContext() : 
				base(global::PM_QLPM.Properties.Settings.Default.DB_QLPMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLPM_ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPM_ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPM_ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPM_ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BENH> BENHs
		{
			get
			{
				return this.GetTable<BENH>();
			}
		}
		
		public System.Data.Linq.Table<CACHDUNG> CACHDUNGs
		{
			get
			{
				return this.GetTable<CACHDUNG>();
			}
		}
		
		public System.Data.Linq.Table<DONVI> DONVIs
		{
			get
			{
				return this.GetTable<DONVI>();
			}
		}
		
		public System.Data.Linq.Table<HOSOBENHNHAN> HOSOBENHNHANs
		{
			get
			{
				return this.GetTable<HOSOBENHNHAN>();
			}
		}
		
		public System.Data.Linq.Table<THAMSO> THAMSOs
		{
			get
			{
				return this.GetTable<THAMSO>();
			}
		}
		
		public System.Data.Linq.Table<TONGHOP_BENHNHAN> TONGHOP_BENHNHANs
		{
			get
			{
				return this.GetTable<TONGHOP_BENHNHAN>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPTHUOC> PHIEUNHAPTHUOCs
		{
			get
			{
				return this.GetTable<PHIEUNHAPTHUOC>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUKHAMBENH> PHIEUKHAMBENHs
		{
			get
			{
				return this.GetTable<PHIEUKHAMBENH>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUNHAPTHUOC> CT_PHIEUNHAPTHUOCs
		{
			get
			{
				return this.GetTable<CT_PHIEUNHAPTHUOC>();
			}
		}
		
		public System.Data.Linq.Table<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENHs
		{
			get
			{
				return this.GetTable<CT_PHIEUKHAMBENH>();
			}
		}
		
		public System.Data.Linq.Table<THUOC> THUOCs
		{
			get
			{
				return this.GetTable<THUOC>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BENH")]
	public partial class BENH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Benh;
		
		private string _TenBenh;
		
		private EntitySet<PHIEUKHAMBENH> _PHIEUKHAMBENHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_BenhChanging(string value);
    partial void OnMa_BenhChanged();
    partial void OnTenBenhChanging(string value);
    partial void OnTenBenhChanged();
    #endregion
		
		public BENH()
		{
			this._PHIEUKHAMBENHs = new EntitySet<PHIEUKHAMBENH>(new Action<PHIEUKHAMBENH>(this.attach_PHIEUKHAMBENHs), new Action<PHIEUKHAMBENH>(this.detach_PHIEUKHAMBENHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Benh", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Benh
		{
			get
			{
				return this._Ma_Benh;
			}
			set
			{
				if ((this._Ma_Benh != value))
				{
					this.OnMa_BenhChanging(value);
					this.SendPropertyChanging();
					this._Ma_Benh = value;
					this.SendPropertyChanged("Ma_Benh");
					this.OnMa_BenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenBenh
		{
			get
			{
				return this._TenBenh;
			}
			set
			{
				if ((this._TenBenh != value))
				{
					this.OnTenBenhChanging(value);
					this.SendPropertyChanging();
					this._TenBenh = value;
					this.SendPropertyChanged("TenBenh");
					this.OnTenBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENH_PHIEUKHAMBENH", Storage="_PHIEUKHAMBENHs", ThisKey="Ma_Benh", OtherKey="Ma_Benh")]
		public EntitySet<PHIEUKHAMBENH> PHIEUKHAMBENHs
		{
			get
			{
				return this._PHIEUKHAMBENHs;
			}
			set
			{
				this._PHIEUKHAMBENHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUKHAMBENHs(PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.BENH = this;
		}
		
		private void detach_PHIEUKHAMBENHs(PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.BENH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CACHDUNG")]
	public partial class CACHDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_CachDung;
		
		private string _TenCachDung;
		
		private EntitySet<CT_PHIEUKHAMBENH> _CT_PHIEUKHAMBENHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_CachDungChanging(string value);
    partial void OnMa_CachDungChanged();
    partial void OnTenCachDungChanging(string value);
    partial void OnTenCachDungChanged();
    #endregion
		
		public CACHDUNG()
		{
			this._CT_PHIEUKHAMBENHs = new EntitySet<CT_PHIEUKHAMBENH>(new Action<CT_PHIEUKHAMBENH>(this.attach_CT_PHIEUKHAMBENHs), new Action<CT_PHIEUKHAMBENH>(this.detach_CT_PHIEUKHAMBENHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_CachDung", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_CachDung
		{
			get
			{
				return this._Ma_CachDung;
			}
			set
			{
				if ((this._Ma_CachDung != value))
				{
					this.OnMa_CachDungChanging(value);
					this.SendPropertyChanging();
					this._Ma_CachDung = value;
					this.SendPropertyChanged("Ma_CachDung");
					this.OnMa_CachDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCachDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCachDung
		{
			get
			{
				return this._TenCachDung;
			}
			set
			{
				if ((this._TenCachDung != value))
				{
					this.OnTenCachDungChanging(value);
					this.SendPropertyChanging();
					this._TenCachDung = value;
					this.SendPropertyChanged("TenCachDung");
					this.OnTenCachDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CACHDUNG_CT_PHIEUKHAMBENH", Storage="_CT_PHIEUKHAMBENHs", ThisKey="Ma_CachDung", OtherKey="Ma_CachDung")]
		public EntitySet<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENHs
		{
			get
			{
				return this._CT_PHIEUKHAMBENHs;
			}
			set
			{
				this._CT_PHIEUKHAMBENHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.CACHDUNG = this;
		}
		
		private void detach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.CACHDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVI")]
	public partial class DONVI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_DonVi;
		
		private string _TenDonVi;
		
		private EntitySet<THUOC> _THUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_DonViChanging(string value);
    partial void OnMa_DonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    #endregion
		
		public DONVI()
		{
			this._THUOCs = new EntitySet<THUOC>(new Action<THUOC>(this.attach_THUOCs), new Action<THUOC>(this.detach_THUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_DonVi", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_DonVi
		{
			get
			{
				return this._Ma_DonVi;
			}
			set
			{
				if ((this._Ma_DonVi != value))
				{
					this.OnMa_DonViChanging(value);
					this.SendPropertyChanging();
					this._Ma_DonVi = value;
					this.SendPropertyChanged("Ma_DonVi");
					this.OnMa_DonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this.OnTenDonViChanging(value);
					this.SendPropertyChanging();
					this._TenDonVi = value;
					this.SendPropertyChanged("TenDonVi");
					this.OnTenDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVI_THUOC", Storage="_THUOCs", ThisKey="Ma_DonVi", OtherKey="Ma_DonVi")]
		public EntitySet<THUOC> THUOCs
		{
			get
			{
				return this._THUOCs;
			}
			set
			{
				this._THUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.DONVI = this;
		}
		
		private void detach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.DONVI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSOBENHNHAN")]
	public partial class HOSOBENHNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_BenhNhan;
		
		private string _Hoten;
		
		private bool _GioiTinh;
		
		private System.DateTime _NamSinh;
		
		private string _DiaChi;
		
		private EntitySet<PHIEUKHAMBENH> _PHIEUKHAMBENHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_BenhNhanChanging(string value);
    partial void OnMa_BenhNhanChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(System.DateTime value);
    partial void OnNamSinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public HOSOBENHNHAN()
		{
			this._PHIEUKHAMBENHs = new EntitySet<PHIEUKHAMBENH>(new Action<PHIEUKHAMBENH>(this.attach_PHIEUKHAMBENHs), new Action<PHIEUKHAMBENH>(this.detach_PHIEUKHAMBENHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_BenhNhan", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_BenhNhan
		{
			get
			{
				return this._Ma_BenhNhan;
			}
			set
			{
				if ((this._Ma_BenhNhan != value))
				{
					this.OnMa_BenhNhanChanging(value);
					this.SendPropertyChanging();
					this._Ma_BenhNhan = value;
					this.SendPropertyChanged("Ma_BenhNhan");
					this.OnMa_BenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Date NOT NULL")]
		public System.DateTime NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSOBENHNHAN_PHIEUKHAMBENH", Storage="_PHIEUKHAMBENHs", ThisKey="Ma_BenhNhan", OtherKey="Ma_BenhNhan")]
		public EntitySet<PHIEUKHAMBENH> PHIEUKHAMBENHs
		{
			get
			{
				return this._PHIEUKHAMBENHs;
			}
			set
			{
				this._PHIEUKHAMBENHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUKHAMBENHs(PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.HOSOBENHNHAN = this;
		}
		
		private void detach_PHIEUKHAMBENHs(PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.HOSOBENHNHAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THAMSO")]
	public partial class THAMSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SLBenhNhan;
		
		private decimal _TienKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSLBenhNhanChanging(int value);
    partial void OnSLBenhNhanChanged();
    partial void OnTienKhamChanging(decimal value);
    partial void OnTienKhamChanged();
    #endregion
		
		public THAMSO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBenhNhan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SLBenhNhan
		{
			get
			{
				return this._SLBenhNhan;
			}
			set
			{
				if ((this._SLBenhNhan != value))
				{
					this.OnSLBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._SLBenhNhan = value;
					this.SendPropertyChanged("SLBenhNhan");
					this.OnSLBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienKham", DbType="Money NOT NULL", IsPrimaryKey=true)]
		public decimal TienKham
		{
			get
			{
				return this._TienKham;
			}
			set
			{
				if ((this._TienKham != value))
				{
					this.OnTienKhamChanging(value);
					this.SendPropertyChanging();
					this._TienKham = value;
					this.SendPropertyChanged("TienKham");
					this.OnTienKhamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TONGHOP_BENHNHAN")]
	public partial class TONGHOP_BENHNHAN
	{
		
		private string _Ma_PhieuKham;
		
		private string _Ma_BenhNhan;
		
		private string _Hoten;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NamSinh;
		
		private string _DiaChi;
		
		private string _TenBenh;
		
		private string _TrieuChung;
		
		public TONGHOP_BENHNHAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuKham", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string Ma_PhieuKham
		{
			get
			{
				return this._Ma_PhieuKham;
			}
			set
			{
				if ((this._Ma_PhieuKham != value))
				{
					this._Ma_PhieuKham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_BenhNhan", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string Ma_BenhNhan
		{
			get
			{
				return this._Ma_BenhNhan;
			}
			set
			{
				if ((this._Ma_BenhNhan != value))
				{
					this._Ma_BenhNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenh", DbType="NVarChar(50)")]
		public string TenBenh
		{
			get
			{
				return this._TenBenh;
			}
			set
			{
				if ((this._TenBenh != value))
				{
					this._TenBenh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChung", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TrieuChung
		{
			get
			{
				return this._TrieuChung;
			}
			set
			{
				if ((this._TrieuChung != value))
				{
					this._TrieuChung = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPTHUOC")]
	public partial class PHIEUNHAPTHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_PhieuNhap;
		
		private System.DateTime _NgayNhap;
		
		private EntitySet<CT_PHIEUNHAPTHUOC> _CT_PHIEUNHAPTHUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_PhieuNhapChanging(string value);
    partial void OnMa_PhieuNhapChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    #endregion
		
		public PHIEUNHAPTHUOC()
		{
			this._CT_PHIEUNHAPTHUOCs = new EntitySet<CT_PHIEUNHAPTHUOC>(new Action<CT_PHIEUNHAPTHUOC>(this.attach_CT_PHIEUNHAPTHUOCs), new Action<CT_PHIEUNHAPTHUOC>(this.detach_CT_PHIEUNHAPTHUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuNhap", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PhieuNhap
		{
			get
			{
				return this._Ma_PhieuNhap;
			}
			set
			{
				if ((this._Ma_PhieuNhap != value))
				{
					this.OnMa_PhieuNhapChanging(value);
					this.SendPropertyChanging();
					this._Ma_PhieuNhap = value;
					this.SendPropertyChanged("Ma_PhieuNhap");
					this.OnMa_PhieuNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPTHUOC_CT_PHIEUNHAPTHUOC", Storage="_CT_PHIEUNHAPTHUOCs", ThisKey="Ma_PhieuNhap", OtherKey="Ma_PhieuNhap")]
		public EntitySet<CT_PHIEUNHAPTHUOC> CT_PHIEUNHAPTHUOCs
		{
			get
			{
				return this._CT_PHIEUNHAPTHUOCs;
			}
			set
			{
				this._CT_PHIEUNHAPTHUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PHIEUNHAPTHUOCs(CT_PHIEUNHAPTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPTHUOC = this;
		}
		
		private void detach_CT_PHIEUNHAPTHUOCs(CT_PHIEUNHAPTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPTHUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_HoaDon;
		
		private string _Ma_PhieuKham;
		
		private decimal _TienKham;
		
		private decimal _TienThuoc;
		
		private string _GhiChu;
		
		private EntityRef<PHIEUKHAMBENH> _PHIEUKHAMBENH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_HoaDonChanging(string value);
    partial void OnMa_HoaDonChanged();
    partial void OnMa_PhieuKhamChanging(string value);
    partial void OnMa_PhieuKhamChanged();
    partial void OnTienKhamChanging(decimal value);
    partial void OnTienKhamChanged();
    partial void OnTienThuocChanging(decimal value);
    partial void OnTienThuocChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public HOADON()
		{
			this._PHIEUKHAMBENH = default(EntityRef<PHIEUKHAMBENH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HoaDon", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_HoaDon
		{
			get
			{
				return this._Ma_HoaDon;
			}
			set
			{
				if ((this._Ma_HoaDon != value))
				{
					this.OnMa_HoaDonChanging(value);
					this.SendPropertyChanging();
					this._Ma_HoaDon = value;
					this.SendPropertyChanged("Ma_HoaDon");
					this.OnMa_HoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuKham", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PhieuKham
		{
			get
			{
				return this._Ma_PhieuKham;
			}
			set
			{
				if ((this._Ma_PhieuKham != value))
				{
					if (this._PHIEUKHAMBENH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_PhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._Ma_PhieuKham = value;
					this.SendPropertyChanged("Ma_PhieuKham");
					this.OnMa_PhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienKham", DbType="Money NOT NULL")]
		public decimal TienKham
		{
			get
			{
				return this._TienKham;
			}
			set
			{
				if ((this._TienKham != value))
				{
					this.OnTienKhamChanging(value);
					this.SendPropertyChanging();
					this._TienKham = value;
					this.SendPropertyChanged("TienKham");
					this.OnTienKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienThuoc", DbType="Money NOT NULL")]
		public decimal TienThuoc
		{
			get
			{
				return this._TienThuoc;
			}
			set
			{
				if ((this._TienThuoc != value))
				{
					this.OnTienThuocChanging(value);
					this.SendPropertyChanging();
					this._TienThuoc = value;
					this.SendPropertyChanged("TienThuoc");
					this.OnTienThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAMBENH_HOADON", Storage="_PHIEUKHAMBENH", ThisKey="Ma_PhieuKham", OtherKey="Ma_PhieuKham", IsForeignKey=true)]
		public PHIEUKHAMBENH PHIEUKHAMBENH
		{
			get
			{
				return this._PHIEUKHAMBENH.Entity;
			}
			set
			{
				PHIEUKHAMBENH previousValue = this._PHIEUKHAMBENH.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUKHAMBENH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUKHAMBENH.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._PHIEUKHAMBENH.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._Ma_PhieuKham = value.Ma_PhieuKham;
					}
					else
					{
						this._Ma_PhieuKham = default(string);
					}
					this.SendPropertyChanged("PHIEUKHAMBENH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUKHAMBENH")]
	public partial class PHIEUKHAMBENH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_PhieuKham;
		
		private string _Ma_BenhNhan;
		
		private System.DateTime _NgayKham;
		
		private string _TrieuChung;
		
		private string _Ma_Benh;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<CT_PHIEUKHAMBENH> _CT_PHIEUKHAMBENHs;
		
		private EntityRef<BENH> _BENH;
		
		private EntityRef<HOSOBENHNHAN> _HOSOBENHNHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_PhieuKhamChanging(string value);
    partial void OnMa_PhieuKhamChanged();
    partial void OnMa_BenhNhanChanging(string value);
    partial void OnMa_BenhNhanChanged();
    partial void OnNgayKhamChanging(System.DateTime value);
    partial void OnNgayKhamChanged();
    partial void OnTrieuChungChanging(string value);
    partial void OnTrieuChungChanged();
    partial void OnMa_BenhChanging(string value);
    partial void OnMa_BenhChanged();
    #endregion
		
		public PHIEUKHAMBENH()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._CT_PHIEUKHAMBENHs = new EntitySet<CT_PHIEUKHAMBENH>(new Action<CT_PHIEUKHAMBENH>(this.attach_CT_PHIEUKHAMBENHs), new Action<CT_PHIEUKHAMBENH>(this.detach_CT_PHIEUKHAMBENHs));
			this._BENH = default(EntityRef<BENH>);
			this._HOSOBENHNHAN = default(EntityRef<HOSOBENHNHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuKham", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PhieuKham
		{
			get
			{
				return this._Ma_PhieuKham;
			}
			set
			{
				if ((this._Ma_PhieuKham != value))
				{
					this.OnMa_PhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._Ma_PhieuKham = value;
					this.SendPropertyChanged("Ma_PhieuKham");
					this.OnMa_PhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_BenhNhan", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string Ma_BenhNhan
		{
			get
			{
				return this._Ma_BenhNhan;
			}
			set
			{
				if ((this._Ma_BenhNhan != value))
				{
					if (this._HOSOBENHNHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_BenhNhanChanging(value);
					this.SendPropertyChanging();
					this._Ma_BenhNhan = value;
					this.SendPropertyChanged("Ma_BenhNhan");
					this.OnMa_BenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChung", DbType="NVarChar(MAX)")]
		public string TrieuChung
		{
			get
			{
				return this._TrieuChung;
			}
			set
			{
				if ((this._TrieuChung != value))
				{
					this.OnTrieuChungChanging(value);
					this.SendPropertyChanging();
					this._TrieuChung = value;
					this.SendPropertyChanged("TrieuChung");
					this.OnTrieuChungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Benh", DbType="NChar(4)")]
		public string Ma_Benh
		{
			get
			{
				return this._Ma_Benh;
			}
			set
			{
				if ((this._Ma_Benh != value))
				{
					if (this._BENH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_BenhChanging(value);
					this.SendPropertyChanging();
					this._Ma_Benh = value;
					this.SendPropertyChanged("Ma_Benh");
					this.OnMa_BenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAMBENH_HOADON", Storage="_HOADONs", ThisKey="Ma_PhieuKham", OtherKey="Ma_PhieuKham")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAMBENH_CT_PHIEUKHAMBENH", Storage="_CT_PHIEUKHAMBENHs", ThisKey="Ma_PhieuKham", OtherKey="Ma_PhieuKham")]
		public EntitySet<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENHs
		{
			get
			{
				return this._CT_PHIEUKHAMBENHs;
			}
			set
			{
				this._CT_PHIEUKHAMBENHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BENH_PHIEUKHAMBENH", Storage="_BENH", ThisKey="Ma_Benh", OtherKey="Ma_Benh", IsForeignKey=true)]
		public BENH BENH
		{
			get
			{
				return this._BENH.Entity;
			}
			set
			{
				BENH previousValue = this._BENH.Entity;
				if (((previousValue != value) 
							|| (this._BENH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BENH.Entity = null;
						previousValue.PHIEUKHAMBENHs.Remove(this);
					}
					this._BENH.Entity = value;
					if ((value != null))
					{
						value.PHIEUKHAMBENHs.Add(this);
						this._Ma_Benh = value.Ma_Benh;
					}
					else
					{
						this._Ma_Benh = default(string);
					}
					this.SendPropertyChanged("BENH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOSOBENHNHAN_PHIEUKHAMBENH", Storage="_HOSOBENHNHAN", ThisKey="Ma_BenhNhan", OtherKey="Ma_BenhNhan", IsForeignKey=true)]
		public HOSOBENHNHAN HOSOBENHNHAN
		{
			get
			{
				return this._HOSOBENHNHAN.Entity;
			}
			set
			{
				HOSOBENHNHAN previousValue = this._HOSOBENHNHAN.Entity;
				if (((previousValue != value) 
							|| (this._HOSOBENHNHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSOBENHNHAN.Entity = null;
						previousValue.PHIEUKHAMBENHs.Remove(this);
					}
					this._HOSOBENHNHAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUKHAMBENHs.Add(this);
						this._Ma_BenhNhan = value.Ma_BenhNhan;
					}
					else
					{
						this._Ma_BenhNhan = default(string);
					}
					this.SendPropertyChanged("HOSOBENHNHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAMBENH = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAMBENH = null;
		}
		
		private void attach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAMBENH = this;
		}
		
		private void detach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUKHAMBENH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUNHAPTHUOC")]
	public partial class CT_PHIEUNHAPTHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_PhieuNhap;
		
		private string _Ma_Thuoc;
		
		private int _SoLuong;
		
		private decimal _DonGia;
		
		private string _GhiChu;
		
		private EntityRef<PHIEUNHAPTHUOC> _PHIEUNHAPTHUOC;
		
		private EntityRef<THUOC> _THUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_PhieuNhapChanging(string value);
    partial void OnMa_PhieuNhapChanged();
    partial void OnMa_ThuocChanging(string value);
    partial void OnMa_ThuocChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CT_PHIEUNHAPTHUOC()
		{
			this._PHIEUNHAPTHUOC = default(EntityRef<PHIEUNHAPTHUOC>);
			this._THUOC = default(EntityRef<THUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuNhap", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PhieuNhap
		{
			get
			{
				return this._Ma_PhieuNhap;
			}
			set
			{
				if ((this._Ma_PhieuNhap != value))
				{
					if (this._PHIEUNHAPTHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_PhieuNhapChanging(value);
					this.SendPropertyChanging();
					this._Ma_PhieuNhap = value;
					this.SendPropertyChanged("Ma_PhieuNhap");
					this.OnMa_PhieuNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Thuoc", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Thuoc
		{
			get
			{
				return this._Ma_Thuoc;
			}
			set
			{
				if ((this._Ma_Thuoc != value))
				{
					if (this._THUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ma_Thuoc = value;
					this.SendPropertyChanged("Ma_Thuoc");
					this.OnMa_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPTHUOC_CT_PHIEUNHAPTHUOC", Storage="_PHIEUNHAPTHUOC", ThisKey="Ma_PhieuNhap", OtherKey="Ma_PhieuNhap", IsForeignKey=true)]
		public PHIEUNHAPTHUOC PHIEUNHAPTHUOC
		{
			get
			{
				return this._PHIEUNHAPTHUOC.Entity;
			}
			set
			{
				PHIEUNHAPTHUOC previousValue = this._PHIEUNHAPTHUOC.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAPTHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAPTHUOC.Entity = null;
						previousValue.CT_PHIEUNHAPTHUOCs.Remove(this);
					}
					this._PHIEUNHAPTHUOC.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPTHUOCs.Add(this);
						this._Ma_PhieuNhap = value.Ma_PhieuNhap;
					}
					else
					{
						this._Ma_PhieuNhap = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAPTHUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CT_PHIEUNHAPTHUOC", Storage="_THUOC", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc", IsForeignKey=true)]
		public THUOC THUOC
		{
			get
			{
				return this._THUOC.Entity;
			}
			set
			{
				THUOC previousValue = this._THUOC.Entity;
				if (((previousValue != value) 
							|| (this._THUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUOC.Entity = null;
						previousValue.CT_PHIEUNHAPTHUOCs.Remove(this);
					}
					this._THUOC.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUNHAPTHUOCs.Add(this);
						this._Ma_Thuoc = value.Ma_Thuoc;
					}
					else
					{
						this._Ma_Thuoc = default(string);
					}
					this.SendPropertyChanged("THUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PHIEUKHAMBENH")]
	public partial class CT_PHIEUKHAMBENH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_PhieuKham;
		
		private string _Ma_Thuoc;
		
		private string _Ma_CachDung;
		
		private short _SoLuong;
		
		private decimal _DonGia;
		
		private string _GhiChu;
		
		private EntityRef<CACHDUNG> _CACHDUNG;
		
		private EntityRef<PHIEUKHAMBENH> _PHIEUKHAMBENH;
		
		private EntityRef<THUOC> _THUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_PhieuKhamChanging(string value);
    partial void OnMa_PhieuKhamChanged();
    partial void OnMa_ThuocChanging(string value);
    partial void OnMa_ThuocChanged();
    partial void OnMa_CachDungChanging(string value);
    partial void OnMa_CachDungChanged();
    partial void OnSoLuongChanging(short value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CT_PHIEUKHAMBENH()
		{
			this._CACHDUNG = default(EntityRef<CACHDUNG>);
			this._PHIEUKHAMBENH = default(EntityRef<PHIEUKHAMBENH>);
			this._THUOC = default(EntityRef<THUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_PhieuKham", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_PhieuKham
		{
			get
			{
				return this._Ma_PhieuKham;
			}
			set
			{
				if ((this._Ma_PhieuKham != value))
				{
					if (this._PHIEUKHAMBENH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_PhieuKhamChanging(value);
					this.SendPropertyChanging();
					this._Ma_PhieuKham = value;
					this.SendPropertyChanged("Ma_PhieuKham");
					this.OnMa_PhieuKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Thuoc", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Thuoc
		{
			get
			{
				return this._Ma_Thuoc;
			}
			set
			{
				if ((this._Ma_Thuoc != value))
				{
					if (this._THUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ma_Thuoc = value;
					this.SendPropertyChanged("Ma_Thuoc");
					this.OnMa_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_CachDung", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string Ma_CachDung
		{
			get
			{
				return this._Ma_CachDung;
			}
			set
			{
				if ((this._Ma_CachDung != value))
				{
					if (this._CACHDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_CachDungChanging(value);
					this.SendPropertyChanging();
					this._Ma_CachDung = value;
					this.SendPropertyChanged("Ma_CachDung");
					this.OnMa_CachDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="SmallInt NOT NULL")]
		public short SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CACHDUNG_CT_PHIEUKHAMBENH", Storage="_CACHDUNG", ThisKey="Ma_CachDung", OtherKey="Ma_CachDung", IsForeignKey=true)]
		public CACHDUNG CACHDUNG
		{
			get
			{
				return this._CACHDUNG.Entity;
			}
			set
			{
				CACHDUNG previousValue = this._CACHDUNG.Entity;
				if (((previousValue != value) 
							|| (this._CACHDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CACHDUNG.Entity = null;
						previousValue.CT_PHIEUKHAMBENHs.Remove(this);
					}
					this._CACHDUNG.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUKHAMBENHs.Add(this);
						this._Ma_CachDung = value.Ma_CachDung;
					}
					else
					{
						this._Ma_CachDung = default(string);
					}
					this.SendPropertyChanged("CACHDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUKHAMBENH_CT_PHIEUKHAMBENH", Storage="_PHIEUKHAMBENH", ThisKey="Ma_PhieuKham", OtherKey="Ma_PhieuKham", IsForeignKey=true)]
		public PHIEUKHAMBENH PHIEUKHAMBENH
		{
			get
			{
				return this._PHIEUKHAMBENH.Entity;
			}
			set
			{
				PHIEUKHAMBENH previousValue = this._PHIEUKHAMBENH.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUKHAMBENH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUKHAMBENH.Entity = null;
						previousValue.CT_PHIEUKHAMBENHs.Remove(this);
					}
					this._PHIEUKHAMBENH.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUKHAMBENHs.Add(this);
						this._Ma_PhieuKham = value.Ma_PhieuKham;
					}
					else
					{
						this._Ma_PhieuKham = default(string);
					}
					this.SendPropertyChanged("PHIEUKHAMBENH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CT_PHIEUKHAMBENH", Storage="_THUOC", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc", IsForeignKey=true)]
		public THUOC THUOC
		{
			get
			{
				return this._THUOC.Entity;
			}
			set
			{
				THUOC previousValue = this._THUOC.Entity;
				if (((previousValue != value) 
							|| (this._THUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUOC.Entity = null;
						previousValue.CT_PHIEUKHAMBENHs.Remove(this);
					}
					this._THUOC.Entity = value;
					if ((value != null))
					{
						value.CT_PHIEUKHAMBENHs.Add(this);
						this._Ma_Thuoc = value.Ma_Thuoc;
					}
					else
					{
						this._Ma_Thuoc = default(string);
					}
					this.SendPropertyChanged("THUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUOC")]
	public partial class THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Thuoc;
		
		private string _TenThuoc;
		
		private int _SoLuong;
		
		private decimal _DonGia;
		
		private string _Ma_DonVi;
		
		private string _GhiChu;
		
		private EntitySet<CT_PHIEUNHAPTHUOC> _CT_PHIEUNHAPTHUOCs;
		
		private EntitySet<CT_PHIEUKHAMBENH> _CT_PHIEUKHAMBENHs;
		
		private EntityRef<DONVI> _DONVI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_ThuocChanging(string value);
    partial void OnMa_ThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnMa_DonViChanging(string value);
    partial void OnMa_DonViChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public THUOC()
		{
			this._CT_PHIEUNHAPTHUOCs = new EntitySet<CT_PHIEUNHAPTHUOC>(new Action<CT_PHIEUNHAPTHUOC>(this.attach_CT_PHIEUNHAPTHUOCs), new Action<CT_PHIEUNHAPTHUOC>(this.detach_CT_PHIEUNHAPTHUOCs));
			this._CT_PHIEUKHAMBENHs = new EntitySet<CT_PHIEUKHAMBENH>(new Action<CT_PHIEUKHAMBENH>(this.attach_CT_PHIEUKHAMBENHs), new Action<CT_PHIEUKHAMBENH>(this.detach_CT_PHIEUKHAMBENHs));
			this._DONVI = default(EntityRef<DONVI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Thuoc", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Thuoc
		{
			get
			{
				return this._Ma_Thuoc;
			}
			set
			{
				if ((this._Ma_Thuoc != value))
				{
					this.OnMa_ThuocChanging(value);
					this.SendPropertyChanging();
					this._Ma_Thuoc = value;
					this.SendPropertyChanged("Ma_Thuoc");
					this.OnMa_ThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_DonVi", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string Ma_DonVi
		{
			get
			{
				return this._Ma_DonVi;
			}
			set
			{
				if ((this._Ma_DonVi != value))
				{
					if (this._DONVI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_DonViChanging(value);
					this.SendPropertyChanging();
					this._Ma_DonVi = value;
					this.SendPropertyChanged("Ma_DonVi");
					this.OnMa_DonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CT_PHIEUNHAPTHUOC", Storage="_CT_PHIEUNHAPTHUOCs", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc")]
		public EntitySet<CT_PHIEUNHAPTHUOC> CT_PHIEUNHAPTHUOCs
		{
			get
			{
				return this._CT_PHIEUNHAPTHUOCs;
			}
			set
			{
				this._CT_PHIEUNHAPTHUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CT_PHIEUKHAMBENH", Storage="_CT_PHIEUKHAMBENHs", ThisKey="Ma_Thuoc", OtherKey="Ma_Thuoc")]
		public EntitySet<CT_PHIEUKHAMBENH> CT_PHIEUKHAMBENHs
		{
			get
			{
				return this._CT_PHIEUKHAMBENHs;
			}
			set
			{
				this._CT_PHIEUKHAMBENHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVI_THUOC", Storage="_DONVI", ThisKey="Ma_DonVi", OtherKey="Ma_DonVi", IsForeignKey=true)]
		public DONVI DONVI
		{
			get
			{
				return this._DONVI.Entity;
			}
			set
			{
				DONVI previousValue = this._DONVI.Entity;
				if (((previousValue != value) 
							|| (this._DONVI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONVI.Entity = null;
						previousValue.THUOCs.Remove(this);
					}
					this._DONVI.Entity = value;
					if ((value != null))
					{
						value.THUOCs.Add(this);
						this._Ma_DonVi = value.Ma_DonVi;
					}
					else
					{
						this._Ma_DonVi = default(string);
					}
					this.SendPropertyChanged("DONVI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PHIEUNHAPTHUOCs(CT_PHIEUNHAPTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = this;
		}
		
		private void detach_CT_PHIEUNHAPTHUOCs(CT_PHIEUNHAPTHUOC entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = null;
		}
		
		private void attach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = this;
		}
		
		private void detach_CT_PHIEUKHAMBENHs(CT_PHIEUKHAMBENH entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_NV;
		
		private string _HoTen;
		
		private string _Username;
		
		private string _Password;
		
		private short _Role;
		
		private string _GhiChu;
		
		private System.Data.Linq.Binary _Avatar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NVChanging(string value);
    partial void OnMa_NVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleChanging(short value);
    partial void OnRoleChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnAvatarChanging(System.Data.Linq.Binary value);
    partial void OnAvatarChanged();
    #endregion
		
		public NHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_NV", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_NV
		{
			get
			{
				return this._Ma_NV;
			}
			set
			{
				if ((this._Ma_NV != value))
				{
					this.OnMa_NVChanging(value);
					this.SendPropertyChanging();
					this._Ma_NV = value;
					this.SendPropertyChanged("Ma_NV");
					this.OnMa_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NChar(64) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(64) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="SmallInt NOT NULL")]
		public short Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
